.PHONY: help up down restart ps logs migrate db-revision db-upgrade seed test test-api health

# Host port mappings
API_URL = http://localhost:8001

help:
	@echo "=========================================================================="
	@echo "                    InfluenceIQ Backend Development CLI                   "
	@echo "=========================================================================="
	@echo "Service Commands:"
	@echo "  make up          - Start all docker containers in the background"
	@echo "  make down        - Tear down and stop all docker containers"
	@echo "  make restart     - Restart all docker containers"
	@echo "  make ps          - View active docker containers status and ports"
	@echo "  make logs        - Tail and follow the API container logs"
	@echo ""
	@echo "Database & Migration Commands:"
	@echo "  make migrate     - Shortcut to run both autogenerate and apply migrations"
	@echo "  make db-revision - Generate a new autogenerated Alembic migration file"
	@echo "  make db-upgrade  - Upgrade database schema to the latest Head migration"
	@echo ""
	@echo "Testing & Seeding Commands:"
	@echo "  make seed        - Trigger hierarchical demo database seeding via REST API"
	@echo "  make test        - Run the resilient WebSocket and event replay integration test"
	@echo "  make test-api    - Run the comprehensive native Python API unit/integration test suite"
	@echo "  make health      - Check detailed system health and Celery queue statuses"
	@echo "=========================================================================="

up:
	docker compose up -d

down:
	docker compose down

restart:
	docker compose restart

ps:
	docker compose ps

logs:
	docker compose logs -f api

db-revision:
	@read -p "Enter migration message: " msg; \
	docker compose exec api alembic revision --autogenerate -m "$$msg"

db-upgrade:
	docker compose exec api alembic upgrade head

migrate:
	@echo "Generating migration..."
	docker compose exec api alembic revision --autogenerate -m "auto_migration"
	@echo "Applying migration..."
	docker compose exec api alembic upgrade head

seed:
	@echo "Seeding/Resetting demo data..."
	@curl -s -X POST $(API_URL)/api/demo/seed | jq || curl -s -X POST $(API_URL)/api/demo/seed

test:
	docker compose exec api python /app/verify_websocket.py

test-api:
	docker compose exec api python /app/test_suite.py

health:
	@curl -s $(API_URL)/health | jq || curl -s $(API_URL)/health
