.PHONY: help up down restart ps logs migrate db-revision db-upgrade seed test test-api test-unit umgl-install umgl health lint

# Host port mappings
API_URL = http://localhost:8002

help:
	@echo "=========================================================================="
	@echo "                    InfluenceIQ Backend Development CLI                   "
	@echo "=========================================================================="
	@echo "Service Commands:"
	@echo "  make up           - Start all docker containers in the background"
	@echo "  make down         - Tear down and stop all docker containers"
	@echo "  make restart      - Restart all docker containers"
	@echo "  make ps           - View active docker containers status and ports"
	@echo "  make logs         - Tail and follow the backend-core container logs"
	@echo ""
	@echo "Database & Migration Commands:"
	@echo "  make migrate      - Shortcut to run both autogenerate and apply migrations"
	@echo "  make db-revision  - Generate a new autogenerated Alembic migration file"
	@echo "  make db-upgrade   - Upgrade database schema to the latest Head migration"
	@echo ""
	@echo "Testing & Linting Commands:"
	@echo "  make seed         - Trigger hierarchical demo database seeding via REST API"
	@echo "  make test         - Run the WebSocket and event replay integration test"
	@echo "  make test-api     - Run the comprehensive Python API unit/integration suite"
	@echo "  make test-unit    - Run the fast offline unit tests (no docker required)"
	@echo "  make health       - Check detailed system health and Celery queue statuses"
	@echo "  make lint         - Run ruff over the whole tree"
	@echo ""
	@echo "Optional Backend:"
	@echo "  make umgl-install - Install the optional umgl_ai ML backend package"
	@echo "  make umgl         - Run the umgl_ai FastAPI service (after umgl-install)"
	@echo "=========================================================================="

up:
	docker compose up -d

down:
	docker compose down

restart:
	docker compose restart

ps:
	docker compose ps

logs:
	docker compose logs -f backend-core

db-revision:
	@read -p "Enter migration message: " msg; \
	docker compose exec backend-core alembic revision --autogenerate -m "$$msg"

db-upgrade:
	docker compose exec backend-core alembic upgrade head

migrate:
	@echo "Generating migration..."
	docker compose exec backend-core alembic revision --autogenerate -m "auto_migration"
	@echo "Applying migration..."
	docker compose exec backend-core alembic upgrade head

seed:
	@echo "Seeding/Resetting demo data..."
	@curl -s -X POST $(API_URL)/api/demo/seed | jq || curl -s -X POST $(API_URL)/api/demo/seed

test:
	docker compose exec backend-core python /workspace/scripts/verify_websocket.py

test-api:
	docker compose exec backend-core python /workspace/scripts/test_suite.py

test-unit:
	PYTHONPATH=. DATABASE_URL=postgresql+psycopg2://x:x@localhost:5432/x \
	  REDIS_URL=redis://localhost:6379/0 \
	  CELERY_BROKER_URL=redis://localhost:6379/0 \
	  CELERY_RESULT_BACKEND=redis://localhost:6379/1 \
	  QDRANT_URL=http://localhost:6333 \
	  python3 -m pytest tests/test_role4_scraping.py tests/test_role5.py \
	                     tests/test_celery_tasks.py tests/test_app_smoke.py \
	                     scoring_service/tests/ -q

lint:
	@command -v ruff >/dev/null 2>&1 || { echo "Install ruff: pip install ruff"; exit 1; }
	ruff check .

umgl-install:
	pip install -e ./umgl_ai

umgl:
	@if [ ! -d "umgl_ai" ]; then \
	  echo "Run 'make umgl-install' first."; exit 1; \
	fi
	UMGL_AI_ROLE=all python3 -m umgl_ai.api

health:
	@curl -s $(API_URL)/health | jq || curl -s $(API_URL)/health
