.PHONY: help up down restart ps logs migrate db-revision db-upgrade seed test test-api test-unit test-ml ml-install ml-run health lint sync

# Host port mappings
API_URL = http://localhost:8002
UV_BACKEND = uv --project backend
COMPOSE = docker compose --env-file backend/.env

help:
	@echo "=========================================================================="
	@echo "                    InfluenceIQ Backend Development CLI                   "
	@echo "=========================================================================="
	@echo "Service Commands:"
	@echo "  make up           - Start all docker containers in the background"
	@echo "  make down         - Tear down and stop all docker containers"
	@echo "  make restart      - Restart all docker containers"
	@echo "  make ps           - View active docker containers status and ports"
	@echo "  make logs         - Tail and follow the backend-core container logs"
	@echo ""
	@echo "Database & Migration Commands:"
	@echo "  make migrate      - Shortcut to run both autogenerate and apply migrations"
	@echo "  make db-revision  - Generate a new autogenerated Alembic migration file"
	@echo "  make db-upgrade   - Upgrade database schema to the latest Head migration"
	@echo ""
	@echo "Testing & Linting Commands:"
	@echo "  make seed         - Trigger hierarchical demo database seeding via REST API"
	@echo "  make test         - Run the WebSocket and event replay integration test"
	@echo "  make test-api     - Run the comprehensive Python API unit/integration suite"
	@echo "  make test-unit    - Run the fast offline unit tests (no docker required)"
	@echo "  make test-ml      - Run the optional backend.ml tests"
	@echo "  make sync         - Create/update the backend uv environment with dev deps"
	@echo "  make health       - Check detailed system health and Celery queue statuses"
	@echo "  make lint         - Run ruff over the whole tree"
	@echo ""
	@echo "Optional Backend:"
	@echo "  make ml-install   - No-op: backend.ml is in-tree; sync runtime deps if needed"
	@echo "  make ml-run       - Run the backend.ml FastAPI service"
	@echo "=========================================================================="

sync:
	$(UV_BACKEND) sync --dev

up:
	$(COMPOSE) up -d

up-build:
	$(COMPOSE) up --build -d --remove-orphans

down:
	$(COMPOSE) down

restart:
	$(COMPOSE) restart

ps:
	$(COMPOSE) ps

logs:
	$(COMPOSE) logs -f backend-core

db-revision:
	@read -p "Enter migration message: " msg; \
	$(COMPOSE) exec backend-core uv run --project backend alembic -c backend/alembic.ini revision --autogenerate -m "$$msg"

db-upgrade:
	$(COMPOSE) exec backend-core uv run --project backend alembic -c backend/alembic.ini upgrade head

migrate:
	@echo "Generating migration..."
	$(COMPOSE) exec backend-core uv run --project backend alembic -c backend/alembic.ini revision --autogenerate -m "auto_migration"
	@echo "Applying migration..."
	$(COMPOSE) exec backend-core uv run --project backend alembic -c backend/alembic.ini upgrade head

seed:
	@echo "Seeding/Resetting demo data..."
	@curl -s -X POST $(API_URL)/api/demo/seed | jq || curl -s -X POST $(API_URL)/api/demo/seed

test:
	$(COMPOSE) exec backend-core uv run --project backend python /workspace/scripts/verify_websocket.py

test-pipeline:
	$(COMPOSE) exec backend-core uv run --project backend python /workspace/scripts/smoke_campaign.py

test-api:
	$(COMPOSE) exec backend-core uv run --project backend python /workspace/scripts/test_suite.py

test-unit:
	PYTHONPATH=./backend DATABASE_URL=postgresql+psycopg://x:x@localhost:5432/x \
	  REDIS_URL=redis://localhost:6379/0 \
	  CELERY_BROKER_URL=redis://localhost:6379/0 \
	  CELERY_RESULT_BACKEND=redis://localhost:6379/1 \
	  QDRANT_URL=http://localhost:6333 \
	  $(UV_BACKEND) run pytest backend/tests/api/test_smoke.py \
	                        backend/tests/api/test_phase1_foundation.py \
	                        backend/tests/api/test_phase3_api_surface.py \
	                        backend/tests/api/test_phase4_websocket.py \
	                        backend/tests/core/ \
	                        backend/tests/pipeline/ -q

test-ml:
	PYTHONPATH=./backend DATABASE_URL=postgresql+psycopg://x:x@localhost:5432/x \
	  REDIS_URL=redis://localhost:6379/0 \
	  CELERY_BROKER_URL=redis://localhost:6379/0 \
	  CELERY_RESULT_BACKEND=redis://localhost:6379/1 \
	  QDRANT_URL=http://localhost:6333 \
	  $(UV_BACKEND) run pytest backend/tests/ml/ -q

lint:
	cd backend && uv run --project . ruff check --config ruff.toml . ../scripts

ml-install:
	@echo "backend.ml is in-tree and has no separate package metadata."
	@echo "Use 'make sync' for core deps; add ML-only deps separately if you enable them."

ml-run:
	@if [ ! -d "backend/ml" ]; then \
	  echo "backend/ml is missing."; exit 1; \
	fi
	ML_ROLE=all $(UV_BACKEND) run python -m backend.ml.api

health:
	@curl -s $(API_URL)/health | jq || curl -s $(API_URL)/health
