"""initial_schema

Revision ID: ca1cf6c2d168
Revises: None
Create Date: 2026-05-22 17:58:17.487074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca1cf6c2d168'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_api_key'), 'brands', ['api_key'], unique=True)
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('niche', sa.String(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('preferred_platforms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('credential_type', sa.String(), nullable=False),
    sa.Column('credential_value', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credential_verifications_influencer', 'credential_verifications', ['influencer_id'], unique=False)
    op.create_table('brand_safety_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('risk_type', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_brand_safety_campaign', 'brand_safety_flags', ['campaign_id'], unique=False)
    op.create_index('idx_brand_safety_influencer', 'brand_safety_flags', ['influencer_id'], unique=False)
    op.create_table('crawl_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_sources_campaign', 'crawl_sources', ['campaign_id'], unique=False)
    op.create_index('idx_crawl_sources_url', 'crawl_sources', ['url'], unique=False)
    op.create_table('influencer_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('brand_safety_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('data_source_count', sa.Integer(), nullable=False),
    sa.Column('score_version', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_influencer_scores_campaign', 'influencer_scores', ['campaign_id'], unique=False)
    op.create_index('idx_influencer_scores_influencer', 'influencer_scores', ['influencer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_influencer_scores_influencer', table_name='influencer_scores')
    op.drop_index('idx_influencer_scores_campaign', table_name='influencer_scores')
    op.drop_table('influencer_scores')
    op.drop_index('idx_crawl_sources_url', table_name='crawl_sources')
    op.drop_index('idx_crawl_sources_campaign', table_name='crawl_sources')
    op.drop_table('crawl_sources')
    op.drop_index('idx_brand_safety_influencer', table_name='brand_safety_flags')
    op.drop_index('idx_brand_safety_campaign', table_name='brand_safety_flags')
    op.drop_table('brand_safety_flags')
    op.drop_index('idx_credential_verifications_influencer', table_name='credential_verifications')
    op.drop_table('credential_verifications')
    op.drop_table('campaigns')
    op.drop_table('influencers')
    op.drop_index(op.f('ix_brands_api_key'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
