export type InfluencerRecommendation = {
  id: string;
  name: string;
  handle: string;
  platform: string;
  followers: number;
  engagementRate: number;
  matchScore: number;
  trustGrade: "A+" | "A" | "B" | "C" | "D";
  brandSafetyFlags: string[];
  citations: string[];
  rate: string;
  deepAnalysisReady?: boolean;
  deepAnalysisBlockReason?: string | null;
  platformPostCount?: number;
  platformCommentCount?: number;
  subScores: Record<string, number>;
  scorePayload: Record<string, unknown>;
  sourcePayload: Record<string, unknown>;
};
